<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1267bffa-38d4-4cbc-902d-217438a4f499</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.Identity" Version="1.20.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.50.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.5" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="local.settings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" Condition="Exists('local.settings.json')" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SouthBaySoccer.Application\SouthBaySoccer.Application.csproj" />
    <ProjectReference Include="..\SouthBaySoccer.Infrastructure\SouthBaySoccer.Infrastructure.csproj" />
    <ProjectReference Include="..\SouthBaySoccer.Contracts\SouthBaySoccer.Contracts.csproj" />
  </ItemGroup>
</Project>


